import base64
import uuid
import re
import shutil
from pathlib import Path
from typing import List, Dict, Any
from loguru import logger
from app.services.mineru_client import MinerUWrapper
from app.services.enrichment_service import VLMEnrichmentService
from app.core.config import settings

class ChunkingService:
    def __init__(self):
        self.mineru_client = MinerUWrapper()
        self.vlm_enrichment_service = VLMEnrichmentService()
        # Pattern to capture enriched images: ![title](rel_path)\n\n> **Contextual Description:** analysis
        self.img_pattern = re.compile(r"!\[(.*?)\]\((.*?)\)\n\n> \*\*Contextual Description:\*\* (.*?)(?=\n\n|\Z)", re.DOTALL)

    async def process_pdf_to_chunks(self, pdf_base64: str) -> List[Dict[str, Any]]:
        """
        Parse a PDF file from base64 and return multi-modal chunks.
        """
        job_id = str(uuid.uuid4())
        # Create job-specific temp directory
        job_dir = Path(settings.TEMP_DIR) / f"job_{job_id}"
        job_dir.mkdir(parents=True, exist_ok=True)
        pdf_path = job_dir / "input.pdf"

        try:
            # Decode and save PDF
            logger.info(f"Decoding PDF for job {job_id}")
            pdf_bytes = base64.b64decode(pdf_base64)
            with open(pdf_path, "wb") as f:
                f.write(pdf_bytes)

            # 1. Process with MinerU
            logger.info(f"Processing PDF with MinerU for job {job_id}")
            output_dir = await self.mineru_client.process_pdf(pdf_path)
            
            # 2. Enrich with VLM
            md_files = list(output_dir.rglob("*.md"))
            if not md_files:
                logger.error("No markdown files generated by MinerU")
                return [{"type": "error", "content": "No markdown output generated by MinerU"}]
            
            md_file = md_files[0]
            logger.info(f"Enriching markdown {md_file.name} for job {job_id}")
            root_section = await self.vlm_enrichment_service.enrich_markdown(md_file)

            # 3. Extract multi-modal chunks
            chunks = []
            self._collect_chunks(root_section, md_file.parent, chunks)
            
            logger.info(f"Successfully chunked PDF into {len(chunks)} chunks for job {job_id}")
            return chunks

        except Exception as e:
            logger.error(f"Error in smart_chunking: {e}")
            return [{"type": "error", "content": f"Internal server error: {str(e)}"}]
        finally:
            # Cleanup job directory
            try:
                shutil.rmtree(job_dir, ignore_errors=True)
                # Note: output_dir cleanup could be handled here if we returned it, 
                # but it's currently managed by MinerUWrapper using settings.TEMP_DIR
            except:
                pass

    def _collect_chunks(self, section, base_path: Path, chunks: list):
        content = section.own_content
        # Split content by images, but keep the captured groups
        # parts will be [text, (img_full), text, ...]
        parts = re.split(r"(!\[.*?\]\(.*?\)\n\n> \*\*Contextual Description:\*\* .*?)(?=\n\n|\Z)", content, flags=re.DOTALL)
        
        for part in parts:
            part = part.strip()
            if not part:
                continue
            
            # Try to match the image pattern
            img_match = self.img_pattern.match(part)
            if img_match:
                title, rel_path, analysis = img_match.groups()
                img_abs_path = base_path / rel_path
                
                if img_abs_path.exists():
                    with open(img_abs_path, "rb") as img_f:
                        img_b64 = base64.b64encode(img_f.read()).decode("utf-8")
                    chunks.append({
                        "type": "image",
                        "data": img_b64,
                        "format": "png",
                        "metadata": {
                            "title": title,
                            "analysis": analysis,
                            "section": section.title
                        }
                    })
                else:
                    logger.warning(f"Image file not found: {img_abs_path}")
                    chunks.append({"type": "text", "content": f"[Image not found: {title}]"})
            else:
                # It's a text chunk
                chunks.append({
                    "type": "text",
                    "content": part,
                    "metadata": {
                        "section": section.title,
                        "level": section.level
                    }
                })

        for child in section.children:
            self._collect_chunks(child, base_path, chunks)
