import asyncio
import hashlib
import json
from typing import List, Dict
from pydantic import BaseModel, Field
from openai import AsyncOpenAI, RateLimitError
from app.core.config import settings
from loguru import logger

class CorrectedHeader(BaseModel):
    original_text: str = Field(..., description="The original line text from the document")
    corrected_text: str = Field(..., description="The corrected header line with appropriate number of '#' symbols")
    level: int = Field(..., description="The nesting level (1 for #, 2 for ##, etc.)")

class HeaderRestorationResponse(BaseModel):
    headers: List[CorrectedHeader]

class LLMClient:
    _semaphore = asyncio.Semaphore(5)  # Class-level semaphore for all instances
    _cache = {} # Class-level cache for all instances

    def __init__(self):
        self.client = AsyncOpenAI(
            api_key=settings.LLM_API_KEY, 
            base_url=settings.LLM_HOST_PATH,
            timeout=60.0
        )
        self.model = settings.LLM_MODEL_NAME
        self.max_retries = 3
        self.retry_delay = 5

    def _get_cache_key(self, text: str) -> str:
        return hashlib.sha256(text.encode("utf-8")).hexdigest()

    async def restore_headers(self, potential_headers: List[str]) -> List[CorrectedHeader]:
        """
        Uses LLM to determine the correct header hierarchy for a list of potential header lines.
        Processes in batches to avoid context limits and handle long reasoning.
        """
        if not potential_headers:
            return []

        all_corrected = []
        batch_size = 50 # Process in batches
        
        for i in range(0, len(potential_headers), batch_size):
            batch = potential_headers[i:i + batch_size]
            corrected_batch = await self._restore_headers_batch(batch)
            all_corrected.extend(corrected_batch)
            
        return all_corrected

    async def _restore_headers_batch(self, batch: List[str]) -> List[CorrectedHeader]:
        headers_str = "\n".join(batch)
        
        system_prompt = (
            "You are an expert technical editor. You will receive a list of ordered potential header lines from a markdown generated by mineru. "
            "Some may already have '#' symbols, some may be flat (all level 1), and some may be missing the '#' entirely. "
            "Your task is to analyze the order, identation, and content of header lines to determine the correct nesting hierarchy based on numbering (e.g., 1.1, 2.3.4, #, ##), indentation, and logical flow. "
            "Return a JSON object with a 'headers' field which is a list of objects. Each object must have: 'original_text', 'corrected_text' (with one or multiple '#' symbols representing the level of depth), and 'level' (integer). "
            "CRITICAL: The output must keep the list ordering, and it must be valid JSON."
        )

        user_prompt = f"Potential header lines to restore:\n{headers_str}\n\nTask: Restore the hierarchy by analyzing the order, identation, and content of the header lines, finally return as structured JSON."

        logger.info(f"LLM Request - Header Restoration Batch ({len(batch)} headers)")
        logger.debug(f"System Prompt: {system_prompt}")
        logger.debug(f"User Prompt: {user_prompt}")
        
        for attempt in range(self.max_retries + 1):
            try:
                async with self._semaphore:
                    response = await self.client.chat.completions.create(
                        model=self.model,
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt}
                        ],
                        response_format={"type": "json_object"},
                        temperature=0.1,
                        max_tokens=4096
                    )
                
                content = response.choices[0].message.content
                logger.debug(f"LLM Response Content: {content}")
                data = json.loads(content)
                
                # Use Pydantic to validate the manually parsed JSON
                parsed_response = HeaderRestorationResponse(**data)
                return parsed_response.headers
                
            except RateLimitError as e:
                if attempt < self.max_retries:
                    logger.warning(f"LLM Rate limit hit, retrying in {self.retry_delay}s...")
                    await asyncio.sleep(self.retry_delay)
                    continue
                raise e
            except Exception as e:
                logger.error(f"LLM header restoration batch failed: {e}")
                if attempt == self.max_retries:
                    # Final fallback: return original text as level 1 headers if everything fails
                    return [CorrectedHeader(original_text=h, corrected_text=f"# {h.lstrip('#').strip()}", level=1) for h in batch]
                await asyncio.sleep(self.retry_delay)

    async def summarize(self, text: str, context_summaries: str = "") -> str:
        """
        Summarizes the text. If context_summaries is provided, it's a parent section summary.
        """
        if not text.strip() and not context_summaries.strip():
            return ""

        cache_key = self._get_cache_key(text + context_summaries)
        if cache_key in self._cache:
            logger.debug("LLM cache hit")
            return self._cache[cache_key]

        system_prompt = "You are a document summarization assistant. Summarize the provided text concisely in text paragraph (up to 5 sentences or 100 words)."
        
        user_prompt = f"Text to summarize:\n{text}"
        if context_summaries:
            user_prompt += f"\n\nContext (summaries of sub-sections):\n{context_summaries}"

        for attempt in range(self.max_retries + 1):
            try:
                async with self._semaphore:
                    logger.info(f"LLM Request - Model: {self.model}")
                    response = await self.client.chat.completions.create(
                        model=self.model,
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt}
                        ],
                        temperature=0.3
                    )
                summary = response.choices[0].message.content.strip()
                self._cache[cache_key] = summary
                return summary
            except RateLimitError as e:
                if attempt < self.max_retries:
                    logger.warning(f"LLM Rate limit hit, retrying in {self.retry_delay}s...")
                    await asyncio.sleep(self.retry_delay)
                    continue
                raise e
            except Exception as e:
                logger.error(f"LLM summarization failed: {e}")
                raise e

    async def analyze_table(
        self,
        table_content: str,
        document_summary: str,
        heading_path: str,
        section_summary: str,
        surrounding_text: str
    ) -> str:
        """
        Analyzes a table and returns a technical contextual description.
        """
        system_prompt = (
            "You are a document analysis assistant. Analyze the provided table based on its global and local document context. "
            "Provide a summarized description in text paragraph (up to 5 sentences or 100 words) explaining how the table data supports the document context."
        )

        user_prompt = (
            f"**Document Purpose:** {document_summary}\n"
            f"**Document Catalog:** {heading_path}\n"
            f"**Section Summary:** {section_summary}\n"
            f"**Immediate Text:** {surrounding_text[:500]}\n\n"
            f"**Table Data:**\n{table_content}\n\n"
            "**Task:** Provide a detailed technical description explaining how this table supports the section summary above."
        )

        logger.info("LLM Request - Table Analysis")
        for attempt in range(self.max_retries + 1):
            try:
                async with self._semaphore:
                    response = await self.client.chat.completions.create(
                        model=self.model,
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt}
                        ],
                        temperature=0.3
                    )
                return response.choices[0].message.content.strip()
            except RateLimitError as e:
                if attempt < self.max_retries:
                    logger.warning(f"LLM Rate limit hit, retrying in {self.retry_delay}s...")
                    await asyncio.sleep(self.retry_delay)
                    continue
                raise e
            except Exception as e:
                logger.error(f"LLM table analysis failed: {e}")
                raise e
